console.log("---------------------Question 1-------------------------");
var val1="JavaScript";
var val2="Google chrome";
var val3="Developer Smart";
var wordLengthSquare= val1.length;
var wordLengthSquare1= val2.length;
var wordLengthSquare2= val3.length;
console.log(`The length of "JavaScript": ${wordLengthSquare} `);
console.log(`The square of lenght is : ${wordLengthSquare*wordLengthSquare}`);
console.log(`The length of "Google chrome": ${wordLengthSquare1} `);
console.log(`The square of lenght is : ${wordLengthSquare1*wordLengthSquare1}`);
console.log(`The length of "Developer Smart": ${wordLengthSquare2} `);
console.log(`The square of lenght is : ${wordLengthSquare2*wordLengthSquare2}`);
console.log("---------------------Question 2-------------------------");
var string = "I am Angular Developer";
var string = "I am Angular Developer";
var stringLength = string.length;
var stringWord = string.split(" ");
var stringWordLength = stringWord.length;
console.log(`The string is : ${string} `);
console.log(`The Length of string is : ${stringLength}`);
console.log(`The words in the string : ${stringWordLength}`);
console.log(`The length is divided by words in the string = ${stringLength/stringWordLength}`);
console.log(`The length is multiplication by wors in the string = ${stringLength*stringWordLength}`);